{% set name = "terratorch" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/terratorch-{{ version }}.tar.gz
  sha256: ea50f7abd6898ff84bd912f997a3548398cc8301442495e7a1980f4ec2b0110a

build:
  entry_points:
    - terratorch = terratorch.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - pytorch ==2.7.0
    - torchvision ==0.22.0
    - rioxarray ==0.19.0
    - albumentations ==1.4.6
    - albucore ==0.0.16
    - rasterio ==1.4.3
    - torchmetrics ==1.7.1
    - geopandas ==1.0.1
    - lightly ==1.5.20
    - jsonargparse <=4.35.0
    - h5py ==3.13.0
    - mlflow ==2.22.0
    - lightning ==2.5.1.post0
    - segmentation-models-pytorch <=0.4.0
    - pytest ==8.3.5
    - torchgeo ==0.7.0
    - einops ==0.8.1
    - timm >=1.0.15
    - huggingface_hub
    - tifffile ==2025.3.30

test:
  imports:
    - terratorch
  commands:
    - pip check
    - terratorch --help
  requires:
    - pip

about:
  summary: TerraTorch - A model training toolkit for geospatial tasks
  dev_url: https://github.com/IBM/terratorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Joao-L-S-Almeida
